import type { Metadata } from "next";
import { Inter as InterFont } from "next/font/google";
import "./globals.css";

const Inter = InterFont({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Inter.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
