import type { Metadata } from "next";
import { Inter as InterFont } from "next/font/google";
import "./globals.css";
import {TRPCReactProvider} from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
import {NuqsAdapter} from "nuqs/adapters/next"


const Inter = InterFont({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NuqsAdapter>
       <TRPCReactProvider>
         <html lang="en">
          <body
             className={`${Inter.className}  antialiased`}>
            <Toaster />
            {children}
          </body>
        </html>
      </TRPCReactProvider>
    </NuqsAdapter>
    
    
  );
}
